// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/AppProvider/index.vue')['default']
    Global: typeof import('./src/components/AppProvider/global.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconLogo: typeof import('./src/components/AppIcons/IconLogo.vue')['default']
    MyForm: typeof import('./src/components/MyForm/MyForm.vue')['default']
    MyInput: typeof import('./src/components/MyForm/components/MyInput.vue')['default']
    MyModal: typeof import('./src/components/MyModal/src/MyModal.vue')['default']
    MySelect: typeof import('./src/components/MyForm/components/MySelect.vue')['default']
    MyTable: typeof import('./src/components/MyTable/MyTable.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NTag: typeof import('naive-ui')['NTag']
    NTransfer: typeof import('naive-ui')['NTransfer']
    ScrollX: typeof import('./src/components/Common/ScrollX.vue')['default']
  }
}

export { }
